services:
  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: django_for_js_devs
      POSTGRES_USER: django
      POSTGRES_PASSWORD: django
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U django"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db_data:
